server:
  port: 80


spring:
  devtools:
    restart:
      # 热部署生效
      enabled: true
      # classpath目录下的 WEB-INF文件夹下的内容修改不重启
      exclude: static/**,templates/**
      additional-paths: src/main/java
  datasource:
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/springboot?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
  thymeleaf:
    cache: false
  jackson:
      default-property-inclusion: non_null


  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000ms
    jedis:
      pool:
        max-active: 8  #连接池最大连接数（使用负值表示没有限制）
        min-idle: 0
        max-idle: 8
        max-wait: -1ms


wx:
  appID: wx8c9ee1d3fd8e8514
  appSecret: 9f6acd10a2fed6d1f43cfbba9624c48b
  encodingAESKey: vxQpWI4VltXG9hQmYnEeztSMpuBbCPrTmPLndPk7aYy
  token: vdsfvwe3546gh65677321a3f
  redirectUrl: http://fuhua.natapp1.cc/wx/getOppenid #微信授权URI, 微信官网的网页回调地址写fuhua.natapp1.cc
